import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import importConfig from "./utils/importConfig";
import React from "react";
import { Config } from "./types/Config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "hikko",
  description: "Generated by hikko",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const config: Config = await importConfig();
  metadata.title = config.site_title;
  metadata.description = config.site_description;
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {children}
    </html>
  );
}
